### ISSUE TITLE
How should I link this?

### ISSUE THREAD

**Issue by moritzgloeckl** [ngTrumbitta/ng-bootstrap-to-bootstrap-3#1]
Hi,

what's the best practice to link the CSS? My bootstrap.css is a simple link in my `index.html` I added `@import '~ng-bootstrap-to-bootstrap-3/dist/ng-bootstrap-to-bootstrap-3.min.css';` to `styles.css`.

Are you supposed to link the css like this?

Thanks!

**Comment by trumbitta** [comment]
Hi @moritzgloeckl, 

since your `bootstrap.css` is a link in `index.html`, if you make sure that `ng-bootstrap-to-bootstrap-3.min.css` ends up **after** `bootstrap.css` in the cascade, it should be fine.

**Comment by moritzgloeckl** [comment]
Hi @trumbitta ,

thanks for the fast reply, when I'm using
```
<link rel="stylesheet" type="text/css" href="~ng-bootstrap-to-bootstrap-3/dist/ng-bootstrap-to-bootstrap-3.min.css">`
```
it's not working. I thought maybe there's a better way than importing it in the `style.css`? How are you importing it?

**Comment by trumbitta** [comment]
Can you post your non-working `styles.css` and your `index.html` so I can take a look at it?

**Comment by moritzgloeckl** [comment]
This is working:

```
--- index.html
<head>
  <link rel="stylesheet" type="text/css" href="https://bootswatch.com/flatly/bootstrap.min.css">
</head>
--- styles.css
@import '~ng-bootstrap-to-bootstrap-3/dist/ng-bootstrap-to-bootstrap-3.min.css'; 
body {
 ....
```

This isn't working:

```
--- index.html
<head>
  <link rel="stylesheet" type="text/css" href="https://bootswatch.com/flatly/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href="~ng-bootstrap-to-bootstrap-3/dist/ng-bootstrap-to-bootstrap-3.min.css">
</head>
--- styles.css
body {
 ....
```

**Comment by trumbitta** [comment]
Oh, ok nice.

The first version, if it's working as intended, should be the preferred one. You installed `ng-bootstrap-to-bootstrap-3` via NPM, so it makes sense to import it like that in `styles.css` - a file that `ng cli` and Webpack take care of.

**Comment by moritzgloeckl** [comment]
Ah ok I see! I thought maybe there's a better way to do it. Thank you very much for your help, and thank you for your work on this.

**Comment by trumbitta** [comment]
You could also directly use the `.scss` file(s), and let Webpack compile everything at build time. You'd have to use [bootstrap-sass](https://github.com/twbs/bootstrap-sass) instead of a pre-compiled Bootstrap for that.

But I think your current setup is already ok as it is :)
